CREATE DATABASE QLQCP
USE QLQCP

CREATE TABLE KHACHHANG (
	MAKH NVARCHAR(7) PRIMARY KEY,  
	HOTEN NVARCHAR(50),
	DCHI NVARCHAR(100),
	SDT NVARCHAR(20) UNIQUE, 
	NGAYSINH SMALLDATETIME, 
	DOANHSO INT, 
	NGAYDK SMALLDATETIME, 
	GIOITINH NVARCHAR(5), 
	SOLANTOIQUAN INT, 
	LOAIKH NVARCHAR(10),
	CONSTRAINT FK_LOAIKH_TENLKH FOREIGN KEY (LOAIKH) REFERENCES LOAIKHACHHANG (TENLKH),
	TINHTRANG BIT )

CREATE TABLE NHANVIEN (
	MANV NVARCHAR(4) PRIMARY KEY, 
	HOTEN NVARCHAR(50), 
	DCHI NVARCHAR(100),
	NGVL SMALLDATETIME,
	SDT NVARCHAR(20) UNIQUE,  
	CMND NVARCHAR(20) UNIQUE,
	GIOITINH NVARCHAR(5), 
	LUONG INT, 
	CHUCVU NVARCHAR(20) )

CREATE TABLE MON (
	MAMON NVARCHAR(4) PRIMARY KEY, 
	TENMON NVARCHAR(50) UNIQUE, 
	DVT NVARCHAR(10), 
	SOLANPHUCVU INT,
	GIA INT,
	TINHTRANG BIT )

CREATE TABLE HOADON (
	SOHD NVARCHAR(7) PRIMARY KEY,
	NGHD SMALLDATETIME, 
	MAKH NVARCHAR(7), 
	MANV NVARCHAR(4),
	TRIGIA INT	,
	GIAMGIA INT,
	CONSTRAINT FK_HOADON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
	CONSTRAINT FK_HOADON_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH) )

CREATE TABLE CTHD (
	SOHD NVARCHAR(7) NOT NULL, 
	MAMON NVARCHAR(4) NOT NULL,
	SL INT,
	CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MAMON),
	CONSTRAINT FK_CTHD_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD),
	CONSTRAINT FK_CTHD_MAMON FOREIGN KEY (MAMON) REFERENCES MON (MAMON) ) 

CREATE TABLE TAIKHOAN (
	ID NVARCHAR(4) PRIMARY KEY,
	TENDN NVARCHAR(50) UNIQUE,
	MATKHAU NVARCHAR(100),
	TINHTRANG BIT
	CONSTRAINT FK_TAIKHOAN_MANV FOREIGN KEY (ID) REFERENCES NHANVIEN (MANV) )

CREATE TABLE CHITIEU (
	ID NVARCHAR(7) PRIMARY KEY,
	THOIGIAN SMALLDATETIME NOT NULL,
	NOIDUNG NVARCHAR(100) NOT NULL,
	MANV NVARCHAR(4),
	SOTIEN INT NOT NULL,
	CONSTRAINT FK_TRALUONG_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV) )

ALTER TABLE KHACHHANG
ADD TINHTRANG BIT

CREATE TABLE KHUYENMAI
(
	PHANTRAMKM INT,
	TINHTRANGKM BIT,
	TIENTOIDA INT,
	TINHTRANGTIENTOIDA BIT
)

CREATE TABLE LOAIKHACHHANG
(
	TENLKH NVARCHAR(10) CONSTRAINT PK_TENLKH PRIMARY KEY,
	TIENTICHLUY INT,
	TINHTRANG BIT
)

CREATE TABLE QUAN
(
	TENQUAN NVARCHAR(100),
	LINK NVARCHAR(100),
	DIACHI NVARCHAR(100),
	LOICHAO NVARCHAR(100),
	WIFI NVARCHAR(20)
)

CREATE TABLE THONGBAO
(
	NOIDUNG NVARCHAR(2000),
	TINHTRANG BIT,
	TINHTRANGXEM BIT
)

ALTER TABLE HOADON
ADD TIENMAT INT

INSERT INTO KHUYENMAI VALUES (N'', 0, N'', 0)
INSERT INTO QUAN VALUES (N'', N'', N'', N'', '')
INSERT INTO THONGBAO VALUES (N'', 0, 0)

/*1*/
DROP TABLE LOAIKHACHHANG
/*2*/
/* QUAY LẠI CREATE TABLE */
/*3*/
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_LOAIKH_TENLKH FOREIGN KEY (LOAIKH) REFERENCES LOAIKHACHHANG (TENLKH)
/*4*/
CREATE TRIGGER TRG_INSERT_UPDATE ON LOAIKHACHHANG
FOR INSERT, UPDATE
AS
BEGIN
	UPDATE KHACHHANG
	SET LOAIKH =  
				(
					SELECT TOP 1 (TENLKH)
					FROM LOAIKHACHHANG B
					WHERE B.TINHTRANG = 1 AND KHACHHANG.DOANHSO >= B.TIENTICHLUY
					ORDER BY B.TIENTICHLUY DESC
				)
END
/*5*/
CREATE TRIGGER TRG_INSERT ON KHACHHANG
FOR INSERT
AS
BEGIN
UPDATE KHACHHANG
	SET LOAIKH = 
				(
					SELECT TOP 1 (TENLKH)
					FROM LOAIKHACHHANG B
					WHERE B.TINHTRANG = 1 AND KHACHHANG.DOANHSO >= B.TIENTICHLUY
					ORDER BY B.TIENTICHLUY DESC
				)
	
END
/*6*/
ALTER TABLE TAIKHOAN
ADD EMAIL NVARCHAR(30) NOT NULL UNIQUE, OTP NVARCHAR(10)
/*7*/
ALTER TABLE TAIKHOAN
ALTER COLUMN EMAIL NVARCHAR(30) NOT NULL
/*8*/
ALTER TABLE TAIKHOAN
ADD CONSTRAINT UN UNIQUE (EMAIL)
/*-----------------------------------------------*/
select  A.TENMON, B.SL, A.GIA, (B.SL * A.GIA) as THANHTIEN
from MON A, CTHD B
where (A.MAMON = B.MAMON) and (B.SOHD = 'HD00058')

select TRIGIA, GIAMGIA, TRIGIA - GIAMGIA AS THANHTOAN, MANV, CONVERT(NVARCHAR(10),DAY(NGHD)) + '/' + CONVERT(NVARCHAR(10),MONTH(NGHD)) + '/' + CONVERT(NVARCHAR(10),YEAR(NGHD)) AS NGHD, SOHD,
TIENMAT, TIENMAT - TRIGIA + GIAMGIA AS TIENTHOILAI FROM HOADON
where SOHD = 'HD0001'
select TENQUAN, LINK, DIACHI, LOICHAO, WIFI from QUAN

select  A.TENMON, B.SL, A.GIA, (B.SL * A.GIA) as THANHTIEN from MON A, CTHD B where (A.MAMON = B.MAMON) and (B.SOHD = 'HD00058')

SELECT * FROM NHANVIEN

UPDATE NHANVIEN
SET NGVL = '2020/11/1'
WHERE MANV = 'NV01'

INSERT INTO KHACHHANG VALUES (N'KH0001', N'q', N'qw', N'1', '2020/12/20', 0, '2021/1/2', N'Nam', 0, N'Bạc', 1)
INSERT INTO NHANVIEN VALUES ('NV01', N'g', N'5', '2021/1/3', '5', '5', N'Nam', '5', N'Thu ngân')